version: "3.9"  # optional since v1.27.0
services:    
  obpm-designer:
    image: registry.cn-hangzhou.aliyuncs.com/obpm/obpm-designer-jar:latest  # 阿里云镜像版本
    restart: always
    environment:
      myapps.storage: /storage
      spring.cloud.consul.host: consul
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    networks:
      my-overlay-network:
        aliases:
         - obpm-designer-srv
    ports:
      - "8082:8082"
    volumes:
      - ./storage:/storage
    links:
      - redis
      - mysql
      - consul
      
  obpm-gateway:
    image: registry.cn-hangzhou.aliyuncs.com/obpm/obpm-gateway-jar:latest  # 阿里云镜像版本
    restart: always
    environment:
      myapps.storage: /storage
      spring.cloud.consul.host: consul
    networks:
      my-overlay-network:
        aliases:
         - obpm-gateway-srv
    ports:
      - "8080:8080"
    volumes:
      - ./storage:/storage
    links:
      - redis
      - mysql
      - consul

  obpm-signon:
    image: registry.cn-hangzhou.aliyuncs.com/obpm/obpm-signon-jar:latest  # 阿里云镜像版本
    restart: always
    environment:
      myapps.storage: /storage
      spring.cloud.consul.host: consul
      spring.datasource.url: jdbc:mysql://${DB_HOST}:${DB_PORT}/obpm5?characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
      spring.datasource.username: ${DB_USERNAME}
      spring.datasource.password: ${DB_PASSWORD}
      spring.redis.host: redis
    networks:
      my-overlay-network:
        aliases:
         - obpm-signon-srv
#    ports:
#      - "8010:8010
    volumes:
      - ./storage:/storage
    links:
      - redis
      - mysql
      - consul

  obpm-message:
    image: registry.cn-hangzhou.aliyuncs.com/obpm/obpm-message-jar:latest  # 阿里云镜像版本
    restart: always
    environment:
      myapps.storage: /storage
      spring.activemq.broker-url: tcp://activemq-srv:61616
      spring.cloud.consul.host: consul-srv
      spring.datasource.url: jdbc:mysql://${DB_HOST}:${DB_PORT}/message5?characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
      spring.datasource.username: ${DB_USERNAME}
      spring.datasource.password: ${DB_PASSWORD}
      spring.redis.host: redis-srv
    networks:
      my-overlay-network:
        aliases:
         - obpm-message-srv
#    ports:
#      - "8084:8084"
    volumes:
      - ./storage:/storage
    links:
      - redis
      - mysql
      - consul
      - activemq

  obpm-usercenter:
    image: registry.cn-hangzhou.aliyuncs.com/obpm/obpm-usercenter-jar:latest  # 阿里云镜像版本
    restart: always
    environment:
      myapps.storage: /storage
      spring.cloud.consul.host: consul-srv
      spring.datasource.url: jdbc:mysql://${DB_HOST}:${DB_PORT}/obpm5?characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
      spring.datasource.username: ${DB_USERNAME}
      spring.datasource.password: ${DB_PASSWORD}
    networks:
      my-overlay-network:
        aliases:
         - obpm-usercenter-srv
    ports:
      - 8088:8088  # 暴露端口
    volumes:
      - ./storage:/storage
    links:
      - redis
      - mysql
      - consul

  obpm-runtime:
    image: registry.cn-hangzhou.aliyuncs.com/obpm/obpm-runtime-jar:latest  # 阿里云镜像版本
    restart: always
    environment:
      myapps.storage: /storage
      spring.activemq.broker-url: tcp://activemq-srv:61616
      spring.activemq.user: admin   #activeMq账号
      spring.activemq.password: admin #activeMq密码
      spring.cloud.consul.host: consul-srv
      spring.redis.host: redis-srv
      JAVA_FONTS: /storage/fonts
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    networks:
      my-overlay-network:
        aliases:
         - obpm-runtime-srv
    volumes:
      - ./storage:/storage
      - ./storage/fonts:/usr/local/openjdk-11/lib/fonts/fallback
    links:
      - redis
      - mysql
      - consul
      - activemq
  obpm-manager:
    image: registry.cn-hangzhou.aliyuncs.com/obpm/obpm-manager-jar:latest  # 阿里云镜像版本
    restart: always
    environment:
      myapps.storage: /storage
      spring.activemq.broker-url: tcp://activemq-srv:61616
      spring.activemq.user: admin   #activeMq账号
      spring.activemq.password: admin #activeMq密码
      spring.cloud.consul.host: consul-srv
      spring.redis.host: redis-srv
      JAVA_FONTS: /storage/fonts
    networks:
      my-overlay-network:
        aliases:
         - obpm-manager-srv
    ports:
    - 8087:8087  # 暴露端口
    volumes:
      - ./storage:/storage
    links:
      - obpm-usercenter

  obpm-converter:
    image: registry.cn-hangzhou.aliyuncs.com/obpm/obpm-converter-jar:latest  # 阿里云镜像版本
    restart: always
    environment:
      myapps.storage: /storage
      JAVA_FONTS: /storage/fonts
    networks:
      my-overlay-network:
        aliases:
         - obpm-converter-srv
    ports:
    - 8084:8084  # 暴露端口
    volumes:
      - ./storage:/storage
    links:
      - consul

  obpm-kms:
    image: registry.cn-hangzhou.aliyuncs.com/obpm/obpm-kms-jar:latest  # 阿里云镜像版本
    restart: always
    environment:
      myapps.storage: /storage
      spring.cloud.consul.host: consul-srv
      spring.datasource.url: jdbc:mysql://${DB_HOST}:${DB_PORT}/obpm5?characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
      spring.datasource.username: ${DB_USERNAME}
      spring.datasource.password: ${DB_PASSWORD}
      spring.redis.host: redis-srv
      JAVA_FONTS: /storage/fonts
    networks:
      my-overlay-network:
        aliases:
         - obpm-manager-srv
    ports:
    - 8085:8085  # 暴露端口
    volumes:
      - ./storage:/storage
    links:
      - obpm-usercenter

  consul: # 服务名称，用户自定义
    image: consul:1.15.2  # 镜像版本
#    network_mode: "host"
    restart: always
    container_name: consul_node1
    networks:
      my-overlay-network:
        aliases:
         - consul-srv
    command:  agent -server -bootstrap-expect 1 -bind=0.0.0.0 -ui -client=0.0.0.0
    ports:
    - 8400:8400  # 暴露端口
    - 8500:8500
    volumes: # 挂载
    - ./static:/usr/share/nginx/html
    privileged: true # 这个必须要，解决nginx的文件调用的权限问题

  mysql:
    networks:
      my-overlay-network:
        aliases:
         - mysql-srv
    ports:
      - "3307:3307"
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
#      MYSQL_USER: 'test'
#      MYSQL_PASS: 'test'
    image: "mysql:5.7.16" 
    container_name: mysql
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/my.cnf:/etc/my.cnf"
      - "./mysql/init:/docker-entrypoint-initdb.d"
      
  nginx: # 服务名称，用户自定义
    image: nginx:latest  # 镜像版本
    restart: always
    networks:
      my-overlay-network:
        aliases:
         - nginx-srv
    ports:
    - 80:80  # 暴露端口
    volumes: # 挂载
    - ./nginx/html:/usr/share/nginx/html
    - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    privileged: true # 这个必须要，解决nginx的文件调用的权限问题
    links:
      - obpm-gateway
  redis:
    image: redis
    container_name: my_redis
    restart: always
    networks:
      my-overlay-network:
        aliases:
         - redis-srv
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
  activemq:
    image: webcenter/activemq:5.14.3
    restart: always
    networks:
      my-overlay-network:
        aliases:
         - activemq-srv
    restart: always
    ports:
      - 61613:61613
      - 61616:61616
      - 8161:8161
    #持久化
    volumes:
      - ./activemq/data:/data/activemq
      - ./activemq/log:/var/log/activemq
    #环境变量
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
      - ACTIVEMQ_CONFIG_MINMEMORY=512
      - ACTIVEMQ_CONFIG_MAXMEMORY=2048
      - TZ=Asia/Shanghai
  onlyoffice:
    image: onlyoffice/documentserver:7.3.2
    container_name: onlyoffice
    restart: always
    environment:
      - JWT_ENABLED=false
    volumes:
      - ./onlyoffice/plugins/compare:/var/www/onlyoffice/documentserver/sdkjs-plugins/compare
      - ./onlyoffice/plugins/removerightcopy:/var/www/onlyoffice/documentserver/sdkjs-plugins/removerightcopy
      - ./onlyoffice/logs:/var/log/onlyoffice
      - ./onlyoffice/data:/var/www/onlyoffice/Data
    networks:
      my-overlay-network:
        aliases:
         - onlyoffice-srv
    ports:
      - "1080:80"

volumes:
  storage: {}
networks:
  my-overlay-network:
    driver: overlay