version: "3.9"  # optional since v1.27.0
services:    
  consul: # 服务名称，用户自定义
    image: consul:1.15.2  # 镜像版本
    networks:
      - my-overlay-network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager] ## 常用方式指定 manager或者work节点
    command: >
      agent -server -ui
      -node=consul-server1
      -bootstrap-expect=1
      -client=0.0.0.0
      -data-dir=/consul/data
      -datacenter=dc1
      -bind '{{ GetPrivateInterfaces | include "network" "192.168.1.0/24" | attr "address" }}'
    ports:
    - 8400:8400  # 暴露端口
    - 8500:8500
    #持久化
    volumes:
      - ./consul/data:/consul/data

  mysql:
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager] ## 常用方式指定 manager或者work节点
    networks:
      - my-overlay-network
    ports:
      - "3307:3307"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: Teemlink2010
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
#      MYSQL_USER: 'test'
#      MYSQL_PASS: 'test'
    image: "mysql:5.7.16" 
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/my.cnf:/etc/mysql/my.cnf"
      - "./mysql/init:/docker-entrypoint-initdb.d"
    
  redis:
    image: redis
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager] ## 常用方式指定 manager或者work节点
    networks:
      - my-overlay-network
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data

  activemq:
    image: webcenter/activemq:5.14.3
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager] ## 常用方式指定 manager或者work节点
    networks:
      - my-overlay-network
    ports:
      - 61613:61613
      - 61616:61616
      - 8161:8161
    #持久化
    volumes:
      - ./activemq/data:/data/activemq
      - ./activemq/log:/var/log/activemq
    #环境变量
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
      - ACTIVEMQ_CONFIG_MINMEMORY=512
      - ACTIVEMQ_CONFIG_MAXMEMORY=2048
      - TZ=Asia/Shanghai

  onlyoffice:
    image: onlyoffice/documentserver:7.3.2
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker] ## 常用方式指定 manager或者work节点
    environment:
      - JWT_ENABLED=false
    volumes:
      - ./onlyoffice/plugins/compare:/var/www/onlyoffice/documentserver/sdkjs-plugins/compare
      - ./onlyoffice/plugins/removerightcopy:/var/www/onlyoffice/documentserver/sdkjs-plugins/removerightcopy
      - ./onlyoffice/logs:/var/log/onlyoffice
      - ./onlyoffice/data:/var/www/onlyoffice/Data
    networks:
      - my-overlay-network
    ports:
      - "1080:80"

  obpm-gateway:
    image: registry.cn-hangzhou.aliyuncs.com/obpm/obpm-gateway-jar:latest  # 阿里云镜像版本
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker] ## 常用方式指定 manager或者work节点
    environment:
      myapps.storage: /storage
      spring.cloud.consul.host: consul
    networks:
      - my-overlay-network
    ports:
      - "8080:8080"
    volumes:
      - ./storage:/storage
    links:
      - consul
      
  nginx:
    image: nginx:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager] ## 常用方式指定 manager或者work节点
    restart: always
    networks:
      - my-overlay-network
    ports:
    - 80:80
    volumes:
    - ./nginx/html:/usr/share/nginx/html
    - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    privileged: true # 这个必须要，解决nginx的文件调用的权限问题
    links:
      - obpm-gateway

  obpm-designer:
    image: registry.cn-hangzhou.aliyuncs.com/obpm/obpm-designer-jar:latest  # 阿里云镜像版本
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker] ## 常用方式指定 manager或者work节点
    restart: always
    environment:
      myapps.storage: /storage
      spring.cloud.consul.host: consul
      DB_HOST: mysql
      DB_PORT: 3307
    networks:
      - my-overlay-network
    ports:
      - "8082:8082"
    volumes:
      - ./storage:/storage
    links:
      - redis
      - mysql
      - consul

  obpm-signon:
    image: registry.cn-hangzhou.aliyuncs.com/obpm/obpm-signon-jar:latest  # 阿里云镜像版本
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker] ## 常用方式指定 manager或者work节点
    restart: always
    environment:
      myapps.storage: /storage
      spring.cloud.consul.host: consul
      spring.datasource.url: jdbc:mysql://mysql:3307/obpm5?characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
      spring.datasource.username: root
      spring.datasource.password: Teemlink2010
      spring.redis.host: redis
    networks:
      - my-overlay-network
#    ports:
#      - "8010:8010
    volumes:
      - ./storage:/storage
    links:
      - redis
      - mysql
      - consul

  obpm-message:
    image: registry.cn-hangzhou.aliyuncs.com/obpm/obpm-message-jar:latest  # 阿里云镜像版本
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker] ## 常用方式指定 manager或者work节点
    restart: always
    environment:
      myapps.storage: /storage
      spring.activemq.broker-url: tcp://activemq:61616
      spring.cloud.consul.host: consul
      spring.datasource.url: jdbc:mysql://mysql:3307/message5?characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
      spring.datasource.username: root
      spring.datasource.password: Teemlink2010
      spring.redis.host: redis
    networks:
      - my-overlay-network
#    ports:
#      - "8084:8084"
    volumes:
      - ./storage:/storage
    links:
      - redis
      - mysql
      - consul
      - activemq

  obpm-usercenter:
    image: registry.cn-hangzhou.aliyuncs.com/obpm/obpm-usercenter-jar:latest  # 阿里云镜像版本
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker] ## 常用方式指定 manager或者work节点
    restart: always
    environment:
      myapps.storage: /storage
      spring.cloud.consul.host: consul
      spring.datasource.url: jdbc:mysql://mysql:3307/obpm5?characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
      spring.datasource.username: root
      spring.datasource.password: Teemlink2010
    networks:
      - my-overlay-network
#    ports:
#      - 8088:8088  # 暴露端口
    volumes:
      - ./storage:/storage
    links:
      - redis
      - mysql
      - consul

  obpm-runtime:
    image: registry.cn-hangzhou.aliyuncs.com/obpm/obpm-runtime-jar:latest  # 阿里云镜像版本
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker] ## 常用方式指定 manager或者work节点
    restart: always
    environment:
      myapps.storage: /storage
      spring.activemq.broker-url: tcp://activemq:61616
      spring.activemq.user: admin   #activeMq账号
      spring.activemq.password: admin #activeMq密码
      spring.cloud.consul.host: consul
      spring.redis.host: redis
      JAVA_FONTS: /storage/fonts
      DB_HOST: mysql
      DB_PORT: 3307
    networks:
      - my-overlay-network
    volumes:
      - ./storage:/storage
      - ./storage/fonts:/usr/local/openjdk-11/lib/fonts/fallback
    links:
      - redis
      - mysql
      - consul
      - activemq

  obpm-manager:
    image: registry.cn-hangzhou.aliyuncs.com/obpm/obpm-manager-jar:latest  # 阿里云镜像版本
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker] ## 常用方式指定 manager或者work节点
    restart: always
    environment:
      myapps.storage: /storage
      spring.activemq.broker-url: tcp://activemq:61616
      spring.activemq.user: admin   #activeMq账号
      spring.activemq.password: admin #activeMq密码
      spring.cloud.consul.host: consul
      spring.redis.host: redis
      JAVA_FONTS: /storage/fonts
    networks:
      - my-overlay-network
#    ports:
#    - 8087:8087  # 暴露端口
    volumes:
      - ./storage:/storage
    links:
      - obpm-usercenter

  obpm-converter:
    image: registry.cn-hangzhou.aliyuncs.com/obpm/obpm-converter-jar:latest  # 阿里云镜像版本
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker] ## 常用方式指定 manager或者work节点
    restart: always
    environment:
      myapps.storage: /storage
      spring.cloud.consul.host: consul
      JAVA_FONTS: /storage/fonts
    networks:
      - my-overlay-network
#    ports:
#    - 8084:8084  # 暴露端口
    volumes:
      - ./storage:/storage
    links:
      - consul

  obpm-kms:
    image: registry.cn-hangzhou.aliyuncs.com/obpm/obpm-kms-jar:latest  # 阿里云镜像版本
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker] ## 常用方式指定 manager或者work节点
    restart: always
    environment:
      myapps.storage: /storage
      spring.cloud.consul.host: consul
      spring.datasource.url: jdbc:mysql://mysql:3307/obpm5?characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
      spring.datasource.username: root
      spring.datasource.password: Teemlink2010
      spring.redis.host: redis
      JAVA_FONTS: /storage/fonts
    networks:
      - my-overlay-network
#    ports:
#    - 8085:8085  # 暴露端口
    volumes:
      - ./storage:/storage
    links:
      - obpm-usercenter

volumes:
  storage: {}

networks:
  my-overlay-network:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"
